### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by KAHORIK-tech** [KAHORIK-tech/ChatSpace#15]
#IPアドレス
54.178.85.13

**Comment by mutorisa** [comment]
川越さん、ご提出ありがとうございます！

挙動確認させて頂いたところ、以下４点の不備が見受けられましたので修正をお願いします！

**①トップページサイドバーのNAME進捗状況記載部分の[文字の太さ]を見本と同じようにし、
　[下線]をなくしましょう。**
<img width="921" alt="サイドバー修正" src="https://user-images.githubusercontent.com/65144927/81643246-25ca2f00-9460-11ea-9a1d-fab320a285aa.png">

<img width="921" alt="サイドバー見本" src="https://user-images.githubusercontent.com/65144927/81643257-2cf13d00-9460-11ea-8e3b-7f58fd441284.png">

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

**②メンバー名の前に[ Member:  ]を入れましょう。**
<img width="766" alt="メンバー修正" src="https://user-images.githubusercontent.com/65144927/81643722-1e575580-9461-11ea-9632-fb27e8584161.png">

<img width="766" alt="member見本" src="https://user-images.githubusercontent.com/65144927/81643733-257e6380-9461-11ea-9d12-f25e5ccf3e48.png">

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

**③新規チャットグループの[チャットメンバー]の部分を見本と同じ位置にし、
　太文字にしましょう。**
<img width="983" alt="チャットメンバー修正" src="https://user-images.githubusercontent.com/65144927/81643301-485c4800-9460-11ea-8449-351cf4e258c9.png">

<img width="983" alt="チャットメンバー" src="https://user-images.githubusercontent.com/65144927/81643466-9a04d280-9460-11ea-8ee1-95ab6824489d.png">

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

**④[Edit→更新する→トップページ]と挙動確認するとメッセージ履歴が消えてしまうので
　表示されるようにしましょう。**
<img width="991" alt="トップページ修正後" src="https://user-images.githubusercontent.com/65144927/81644084-092ef680-9462-11ea-862c-7822a9cc2089.png">

<img width="991" alt="トップページ見本" src="https://user-images.githubusercontent.com/65144927/81644064-fd433480-9461-11ea-8ad7-fdc74f0f431f.png">




修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by naru6117** [comment]
ご提出ありがとうございます！

挙動確認させて頂いたところ、前回の指摘事項の修正が確認できませんでした。
デプロイがうまく言っていない場合もあるので、今一度ご確認いただき、本番環境にて修正が確認できましたら、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by mutorisa** [comment]
修正後再度ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！
